apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-server-mcp
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: random-server-mcp
    account: random-server-mcp
